---
title: "hw scrapbook"
output: html_document
---

```{r}
h <- c(28,31,33,33,36,36,37,37,38,38,38,38)
b <- c(19,21,21,22,22,22,24,26,27,27,30,31)
mean <- function(x) {sum(x)/length(x)}
mh <- mean(h)
mb <- mean(b)
sqdev <- function(c, m) {(c-m)^2}
sd(b)
sqdev(b,mb)
se(b)
serror <- function(x) {sd(x)/sqrt(length(x))}
ci95u <- function(x){mean(x)+2*serror(x)}
ci95l <- function(x){mean(x)-2*serror(x)}
mean(b)+serror(b)
```

```{r}
binom.test(8,30,0.35, alternative="less")


x <- c(1,2,3,4,5, 6)
celnofood <- c(20,18,17,12,5,3)
ocnofood <- c(20,19,18,13,6,3)
ocwcelnofood <- c(20,20,19,17,12,8)
celwocnofood <- c(20,17,15,10,5,2,0)
occebt <- c(20,18,16,11,6,2)
ceocbt <- c(20,10,5,0,0,0)
plot(x,celnofood,type="l", xlab="Time (days)", ylab="Worms surviving", main="Survival curves of nematodes")
points(ocnofood, col="dark gray", type="l")
points(ocwcelnofood, col="green", type="l")
points(celwocnofood, col="blue", type="l")
points(occebt, col="purple", type="l")
points(ceocbt, col="red", type="l")
legend(x=4.45,y=21,legend=c("C. elegans no food","O. Carolinensis no food", "O. carolinensis with C. e no food", "C. elegans with O. c no food", "O. carolinensis with C. e Bt4A4","C. elegans with O. c Bt4A4"),lty=1,col=c("black","dark grey", "green", "blue", "purple", "red"),cex=0.6)
```


